services:
  controller:
    build:
      context: .
      args:
        LINUX_USERNAME: $LINUX_USERNAME
        LINUX_PASSWORD: $LINUX_PASSWORD
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 2222:22
